=== jorgefeijoo/lmsxi/XML/tarea7/ej2/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="tipoLibraria">
    <xs:sequence>
      <xs:element name="Titulo" type="xs:string" />
      <xs:element name="Autor" type="xs:string" />
      <xs:element name="Data" type="xs:string" />
      <xs:element name="ISBN" type="tipoISBN" />
      <xs:element name="Editorial" type="xs:string" />
    </xs:sequence>
  </xs:complexType>


  <xs:simpleType name="tipoISBN">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]\-[0-9]{5}\-[0-9]{3}\-[0-9]" />
    </xs:restriction>
  </xs:simpleType>


  <xs:element name="Libraria">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Libro" type="tipoLibraria" minOccurs="0" maxOccurs="2" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jorgefeijoo/lmsxi/XML/tarea7/ej2/document.xml
<?xml version="1.0"?>
<Libraria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="document.xsd">
  <Libro>
    <Titulo>Anso</Titulo>
    <Autor>Gosendo</Autor>
    <Data>19-12-2007</Data>
    <ISBN>1-23456-789-1</ISBN>
    <Editorial>Pacrama</Editorial>

  </Libro>


  <Libro>
    <Titulo>Gorge</Titulo>
    <Autor>Eli</Autor>
    <Data>10-12-2007</Data>
    <ISBN>8-76543-219-8</ISBN>
    <Editorial>Cuñado de eli</Editorial>

  </Libro>

</Libraria>
