=== jorgefeijoo/lmsxi/XML/tarea4/ejercicio 4/ejercicioPintura.dtd
<!ELEMENT pedidos (proovedor, pintura+, data, hora)>
<!ELEMENT proovedor (CIF, nome, domicilio, telefono)>
<!ELEMENT pintura (marca, cor, cantidade)>

<!ELEMENT data (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT CIF (#PCDATA)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT domicilio (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT cor (#PCDATA)>
<!ELEMENT cantidade (#PCDATA)>

=== jorgefeijoo/lmsxi/XML/tarea4/ejercicio 4/ejercicioPintura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "ejercicioPintura.dtd">
<pedidos>

    <proovedor>
        <CIF>A12345678</CIF>
        <nome>Gosendo</nome>
        <domicilio>Os tilos</domicilio>
        <telefono>111111111</telefono>
    </proovedor>

    <pintura>
        <marca>dupont</marca>
        <cor>azul</cor>
        <cantidade>5</cantidade>
    </pintura>

    <pintura>
        <marca>tintanlux</marca>
        <cor>rojo</cor>
        <cantidade>3</cantidade>
    </pintura>

    <data>19-12-2007</data>
    <hora>19:19</hora>



</pedidos>
